run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - gen
    - mocks
  skip-dirs-use-default: true
  modules-download-mode: vendor

linters:
  enable:
    - revive
    - gofmt
    - govet
    - gosec
    - unconvert
    - goconst
    - gocyclo

issues:
  include:
    - EXC0002
